# Generated by Django 2.2.4 on 2019-08-26 09:56

from django.db import migrations
from authentication.models import User

def create_teachers(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User.objects.create_user(username='ann',
                             email='ann@gmail.com',
                             password='ann@123',
                             type='T')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_teachers),
    ]
